// <auto-generated />
using System;
using DataSentry.Data.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataSentry.Data.Persistence.Migrations
{
    [DbContext(typeof(DataSentryDbContext))]
    [Migration("20260712151132_FlagRetentionDeadline")]
    partial class FlagRetentionDeadline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.FileScanResultEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAccessedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RecycledUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RetentionDeadline")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("ReportId", "Recommendation");

                    b.ToTable("FileScanResults", (string)null);
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.PiiFindingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("DetectorName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileScanResultId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileScanResultId");

                    b.ToTable("PiiFindings", (string)null);
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.ScanErrorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ScanErrors", (string)null);
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.ScanReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesNeedingReview")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesRecommendedForDeletion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesScanned")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReclaimableBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CompletedUtc");

                    b.ToTable("ScanReports", (string)null);
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.FileScanResultEntity", b =>
                {
                    b.HasOne("DataSentry.Data.Persistence.Entities.ScanReportEntity", null)
                        .WithMany("Results")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.PiiFindingEntity", b =>
                {
                    b.HasOne("DataSentry.Data.Persistence.Entities.FileScanResultEntity", null)
                        .WithMany("Findings")
                        .HasForeignKey("FileScanResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.ScanErrorEntity", b =>
                {
                    b.HasOne("DataSentry.Data.Persistence.Entities.ScanReportEntity", null)
                        .WithMany("Errors")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.FileScanResultEntity", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("DataSentry.Data.Persistence.Entities.ScanReportEntity", b =>
                {
                    b.Navigation("Errors");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
